steps:
  - name: 'gcr.io/cloud-builders/pip'
    args: ['install','-r','requirements.txt']

  - name: 'gcr.io/cloud-builders/pytest'
    args: ['--cov-report term-missing','--cov=app/','app/tests/']

  - name: 'gcr.io/cloud-builders/pylint'
    args: ['app/']